# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 04:16
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160728_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=blog.models.PhoneNumberField(max_length=20, validators=[blog.models.phone_number_validator, blog.models.phone_number_validator, blog.models.phone_number_validator]),
        ),
    ]
